# Generated by Django 6.1.1 on 2026-09-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_grand_tour_and_horseback'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='лучшее время (нем.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='лучшее время (исп.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='body_de',
            field=models.TextField(blank=True, help_text='Один абзац на строку.', verbose_name='текст (нем.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='body_es',
            field=models.TextField(blank=True, help_text='Один абзац на строку.', verbose_name='текст (исп.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights_de',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='изюминки (нем.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights_es',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='изюминки (исп.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='название (нем.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='название (исп.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='summary_de',
            field=models.TextField(blank=True, verbose_name='краткое описание (нем.)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='summary_es',
            field=models.TextField(blank=True, verbose_name='краткое описание (исп.)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_de',
            field=models.TextField(blank=True, verbose_name='ответ (нем.)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_es',
            field=models.TextField(blank=True, verbose_name='ответ (исп.)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='вопрос (нем.)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='вопрос (исп.)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='alt-текст (нем.)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_es',
            field=models.CharField(blank=True, max_length=300, verbose_name='alt-текст (исп.)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_de',
            field=models.TextField(blank=True, verbose_name='о сотруднике (нем.)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_es',
            field=models.TextField(blank=True, verbose_name='о сотруднике (исп.)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='должность (нем.)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='должность (исп.)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='country_de',
            field=models.CharField(blank=True, max_length=120, verbose_name='страна (нем.)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='country_es',
            field=models.CharField(blank=True, max_length=120, verbose_name='страна (исп.)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_de',
            field=models.TextField(blank=True, verbose_name='отзыв (нем.)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_es',
            field=models.TextField(blank=True, verbose_name='отзыв (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excluded_de',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='не входит (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excluded_es',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='не входит (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights_de',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='изюминки (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights_es',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='изюминки (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_de',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='входит в стоимость (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_es',
            field=models.TextField(blank=True, help_text='Один пункт на строку.', verbose_name='входит в стоимость (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='название (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='название (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='overview_de',
            field=models.TextField(blank=True, help_text='Один абзац на строку.', verbose_name='описание (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='overview_es',
            field=models.TextField(blank=True, help_text='Один абзац на строку.', verbose_name='описание (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='summary_de',
            field=models.TextField(blank=True, verbose_name='краткое описание (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='summary_es',
            field=models.TextField(blank=True, verbose_name='краткое описание (исп.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tagline_de',
            field=models.TextField(blank=True, verbose_name='подзаголовок (нем.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tagline_es',
            field=models.TextField(blank=True, verbose_name='подзаголовок (исп.)'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='текст (нем.)'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='текст (исп.)'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок (нем.)'),
        ),
        migrations.AddField(
            model_name='tourday',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок (исп.)'),
        ),
        migrations.AddField(
            model_name='tournote',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='текст (нем.)'),
        ),
        migrations.AddField(
            model_name='tournote',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='текст (исп.)'),
        ),
        migrations.AddField(
            model_name='tournote',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок (нем.)'),
        ),
        migrations.AddField(
            model_name='tournote',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок (исп.)'),
        ),
    ]
